### ISSUE TITLE
Inactive status pane color

### ISSUE THREAD

**Issue by tadghh** [joelacus/deluge-web-dark-theme#12]
Is this the correct color? It feels like a visual thumbtack, maybe a lighter/more transparent overlay?
![image](https://github.com/joelacus/deluge-web-dark-theme/assets/47073445/a9fb32d6-f167-480b-87a8-82f224a3980d)

**Comment by joelacus** [comment]
Good point, this mask should be black. I modified the original grey theme and missed this bit.
I've uploaded a new version now, just run the install command again and it should be good. If you don't see the change right away, press `CTRL+SHIFT+R` to force reload the files.
Thanks! :)
