### ISSUE TITLE
Feature request - improvement

### ISSUE THREAD

**Issue by Modged** [joelacus/deluge-web-dark-theme#16]
Hello :)
It would be great to add more highlight colors depending on the state of the torrent: error, pause, seeding, downloading, etc.
It would made easier to identify which torrent needs more attention.
By the way thanks for the work done the light theme pissed me so much.

**Comment by joelacus** [comment]
That's a good idea, I can add that no problem :)

**Comment by joelacus** [comment]
I've updated the theme. Just run the install command again to install it.

The row colours are enabled by default, and you can easily edit the colours to whatever you want in this file:
`xtheme-dark.css`. 

I quite like how it looks actually, good suggestion :)

**Comment by Modged** [comment]
That's great, thanks you !! :) I will tell you if i have another idea :)

**Comment by Modged** [comment]
Just discovered the webui is broken on mobile.
Switched to desktop mode to recover don't know if you can fix this but i wanted to let you know.
Not a big issue btw
