### ISSUE TITLE
Instal in docker?

### ISSUE THREAD

**Issue by FloydKulis** [joelacus/deluge-web-dark-theme#2]
Do you know how you can add it to Deluge in Docker version?

**Comment by joelacus** [comment]
Hi, I've never used Docker myself so I'm not sure, but I know it is possible, it's just a question of where the theme files are located. Someone commented on my [reddit post](https://www.reddit.com/r/raspberry_pi/comments/ktcatl/deluge_web_ui_modern_dark_theme/) about this theme saying they got it working in Docker. You could send them a message. I might try Docker myself when I get the time and see. Let me know in the meantime if you figure it out and I can update the read me with the solution :)

**Comment by ghost** [comment]
Hey!
Using `sudo find / -type d -name 'web'` you can find the path used by the docker version.

If there is a container running it'll give you 2 path:
- /var/lib/docker/overlay2/_xxx_/**diff**/usr/lib/python3/dist-packages/deluge/ui/web/
- /var/lib/docker/overlay2/_yyy_/**merged**/usr/lib/python3/dist-packages/deluge/ui/web/
(where xxx and yyy are long strings, directory IDs of image layer or something like that..)

You must replace _/usr/lib/python3/dist-packages/deluge/ui/web/_ in the install command by the path with **diff** in it and then edit your web.conf

I must add that the Docker [documentation](https://docs.docker.com/storage/storagedriver/overlayfs-driver/#how-the-overlay2-driver-works) explicitly says "Warning: Do not directly manipulate any files or directories within /var/lib/docker/. These files and directories are managed by Docker."
(personally I don't care, it's still working...)

If you are not using OverlayFS it will be different, but I think it's the default, at least it's the recommended storage driver.

**Comment by joelacus** [comment]
@b0ywearngtyts thanks for the info! I've updated the readme with new docker install instructions :)
