### ISSUE TITLE
UI is too big

### ISSUE THREAD

**Issue by ImFilippo** [joelacus/deluge-web-dark-theme#6]
Hi, i have successfully installed this theme for the web ui and it works however i have a problem; many cards are too big and therefore you cannot see all the inscriptions inside (see img for example).
How come? can i solve this?
Thank you!

EXAMPLE
![img](https://user-images.githubusercontent.com/49730440/150695884-2f49df13-d889-4f0a-909f-bb443d483725.png)

**Comment by joelacus** [comment]
Hey, sorry about this issue, I missed this one, thanks for letting me know. 
I've made the Options section taller to fit all the options and uploaded the new version. Just run the install command again and it should be fixed. You may have to force reload the site files by pressing CTRL+SHIFT+R while on the deluge web UI to refresh the cache.
Let me know if it works and if you have any other issues :)

**Comment by ImFilippo** [comment]
Thanks for resolving promptly!
Yes, with the new theme I can see everything; there are still a few small burrs here and there (see images) but in general it works well!
It would be great if the rectangle containing the settings can be enlarged, I can only move it and not increase the size.
https://imgur.com/a/XCFgC1B

**Comment by joelacus** [comment]
Hi, I've fixed those issues, and did some other slight improvements as well. Also, the scrollbars should now look more modern :3
Let me know if you can still see any of those issues, and if so, may I ask which browser and what device you are using.
Unfortunately, I can't make the Preferences window resizeable, I can only manipulate the CSS (style) :/
The new version has been uploaded :)

**Comment by ImFilippo** [comment]
Thank you, the new version is much better!
I'm using chrome (97.0.4692.99) on my windows desktop (1440p display).

**Comment by joelacus** [comment]
I'm glad you like it :)
