### ISSUE TITLE
Current Deluge 2.1.1 docker resetting theme in config on start

### ISSUE THREAD

**Issue by martini1992** [joelacus/deluge-web-dark-theme#7]
Using the Deluge docker image from [https://hub.docker.com/r/linuxserver/deluge](https://hub.docker.com/r/linuxserver/deluge) and installing the theme using the volume mounting technique.

On start the theme value in config keeps being reset to "gray".

I've got round this for now by changing the name of the CSS files to "gray" instead of "dark", but this may be worth documenting for others or looking into a permanent fix/workaround.

**Comment by joelacus** [comment]
Hi. In the same directory as the web.conf file, is there another called web.conf~, with a tilde \~? I've noticed this reverts the web.conf file back when Deluge starts. You just need to stop Deluge and delete the web.conf~ file, and re-edit web.conf again. I've noted this for the other installs in the readme, apologies for missing it on the Docker instructions. I hope this is the issue. Let me know if this solution works, thanks.

**Comment by martini1992** [comment]
Ah yes this fixed it.
I was editing the file then restarting the container, what a weird behaviour.
Cheers for the help :)

**Comment by joelacus** [comment]
You're welcome. I'm glad you got it working :)

**Comment by crypticviper** [comment]
Sorry to post on this old issue but I didn't want to start a new one as the issue I face is very similar. I am on unraid and using binhex-deluge container.

My web.conf reverts to "gray" every time I restart my container. There is no web.conf~ anywhere. There is a web.conf.bak file but deleting this file has no effect as it gets recreated upon restart. 

Any ideas?
