### ISSUE TITLE
No web.conf file exists for new install

### ISSUE THREAD

**Issue by NickSChristiansen** [joelacus/deluge-web-dark-theme#8]
I can't edit the web.conf as such a file doesn't exist for a brand new Windows install of Deluge 2.1.1.

**Comment by joelacus** [comment]
Interesting, I tested this on a Window 10 VM with Deluge 2.1.1 and it all works. Are you using Windows 11? Perhaps it stores the file in a different location?

**Comment by NickSChristiansen** [comment]
Yep, Win 11.

**Comment by joelacus** [comment]
I've just tested it on Windows 11 and the file is in the same location as 10. Do you have the Web UI plugin loaded?
It seems the web.conf file will only show when the plugin is loaded. Deluge > Edit > Preferences > Plugins > WebUI.
Then in Preferences > WebUi, check "Enable web interface"

**Comment by NickSChristiansen** [comment]
That did it, thanks! :)

**Comment by joelacus** [comment]
You're welcome :)

**Comment by AQUAMXRINE** [comment]
Hi, I tried to disable it then re-enable but I still don't have a web.conf file, could you please give me the exact location ? Maybe i'm searching it the wrong way... (Win10 & Deluge 2.1.1)
Thanks!
