### ISSUE TITLE
Truenas SCALE

### ISSUE THREAD

**Issue by willyum000** [joelacus/deluge-web-dark-theme#9]
No fileset like you describe for Truenas SCALE. I loved this theme hoping I can use it once again.

**Comment by willyum000** [comment]
Nevermind. I figured it out.
sudo find / -print | egrep 'deluge/ui/web'

then copy that path and unpack the tar into there.

Edit web.conf as normal.

Thanks!

**Comment by joelacus** [comment]
Hey @willyum000,
I like issues that resolve themselves haha. Thanks for pointing this out though, I was unaware of this. 
Will the absolute file path be the same for all TrueNas SCALE systems? Could you provide me with the path so I can update the readme please if so? Thanks

**Comment by willyum000** [comment]
Absolutely friend!
I believe it's going to be different per install.
I'm at work right now (MSP) but I'll be happy to send you all the info when
I get home in a couple of hours.

Talk to you soon,
Will
